### ISSUE TITLE
Press and Release event passed only at finger remove

### ISSUE THREAD

**Issue by DDAAXX** [kergoth/tslib#10]
Hi,
I'm using a capacitive touchscreen with Atmel Maxtouch driver (atmel_mxt_ts.c).
It uses raw_input.
When I press the screen and wait, I have no event emitted by tslib.
When I remove my finger, I have at the same time the press and the release events.
If I test with ts_test, I see:

854.560940:    226    270     49
856.515562:    226    270      0

So it seems that the timestamps are correct (2 seconds from the first and the second event).
Where I can check to find why tslib wait for the release event before to send the press?

Thanks a lot
Dario

**Comment by robgreger** [comment]
Based upon the first post, the controller may only be reporting once when the screen is pressed and once when the screen is released. If that is the case, then the touch controller is doing a great job filtering noise and the variance filter isn't necessary. The dejitter filter might also be unnecessary.

Having said that, the variance filter could be rewritten to pass through the first touch event just like the dejitter filter does.

**Comment by merge** [comment]
I tested this on a capacitive touchscreen too. Fixed in master now, so it'll be in tslib 1.2. If one of you could test again, this would be awesome, but I know it's been a long time. Anyways, I'll keep this open for a few days.

**Comment by merge** [comment]
Closed. In case of problems, I'm happy to see a new bug report against master or 1.2. thanks
