### ISSUE TITLE
To all users: Do you use ANY other module_raw than "input" in your ts.conf?

### ISSUE THREAD

**Issue by merge** [kergoth/tslib#105]
We certainly have useless `module_raw` modules mentioned in [ts.conf](https://github.com/kergoth/tslib/blob/master/etc/ts.conf) and enabled by default `./configure` on Linux. The question is: Which ones are definitely useless enough that people who **do** use them, have them explicitely enabled?

We'll always have `module_raw input` configured in by default in Linux. This is what people **should** be using. This is the **only** module that supports multitouch! Other than that, we have the following candidates I would like to evaluate:

* `module_raw touchkit`
* `module_raw waveshare`

### If you use one of these 2 modules in your `/etc/ts.conf`, please reply here and say so!

Please note that even if we might disable modules from this list, this is only the **default** and they are available via `./configure --enable-arctic2` and so on. We already have the following

* `module_raw galax` (disabled since 1.13. can be safely replaced by `module_raw input`)
* `module_raw dmc_dus3000`
* `module_raw cy8mrln_palmpre`
* `module_raw arctic2` (disabled since 1.14)
* `module_raw collie` (disabled since 1.14)
* `module_raw corgi` (disabled since 1.14)
* `module_raw dmc` (disabled since 1.14)
* `module_raw h3600` (disabled since 1.14)
* `module_raw mk712` (disabled since 1.14)
* `module_raw ucb1x00` (disabled since 1.14)
* `module_raw tatung` (disabled since 1.16)

disabled by default, but available when configured. We will never drop any module or support for any device entirely.

**Comment by craftyguy** [comment]
My application targets Linux, and so I just use the default `module_raw input` since we have not come across any devices that require otherwise to function.

**Comment by merge** [comment]
The low hanging fruits would probably the Linux-specific ones, galax and waveshare. I'll consider disabling them quite soon.

The others are usable on Mac OS and Hurd too.

**Comment by ClayMontgomery** [comment]
My application only uses module_raw input.

**Comment by merge** [comment]
Alright this is running for long enough and we seem to have identified what we want to keep enabled by default. thanks.
