### ISSUE TITLE
Egalax-Patch

### ISSUE THREAD

**Issue by hevilp** [kergoth/tslib#11]
Where is the egalax patch for the actual version?

**Comment by merge** [comment]
Is it one of these?
https://github.com/kergoth/tslib/commit/35714b2a7edff79aabb21ad0291698fd9b654419
https://github.com/kergoth/tslib/commit/da53dfd4d07df99a80dc0acbe5df3b5ade20ab15
https://github.com/kergoth/tslib/commit/6628598bc08ad5eab8549a4c6c682fdec006505e

If so, they're part of tslib's upcoming version 1.2

**Comment by merge** [comment]
This issue is 4 years old. I'll just close it now. Please reopen it with detailed information, if the question is still relevant for tslib 1.2.
