### ISSUE TITLE
ts_uinput: add option to take x/y max values from the input device

### ISSUE THREAD

**Issue by merge** [kergoth/tslib#113]
Point is, I want to make the TSLIB_FBDEVICE and TSLIB_CONSOLEDEVICE environment variables deprecated, at least as soon as `./configure --with-sdl2` is used. ts_uinput uses the framebuffer device for getting x/y maximum values though. What happens if we assume a touchscreen's input device offers the same values?

**Comment by craftyguy** [comment]
Is there a way to test/check the coordinate system for tslib using framebuffer vs tslib getting coordinates directly from touch devices?

**Comment by merge** [comment]
tslib (or the library) itself doesn't really use any coordinate system. It takes x/y values as they come. The device drivers I have seen so far use the same coordinate system for both. Technically it doesn't matter, especially when you apply the `linear` filter (ts_calibrate) anyways. In this case ts_uinput is the device driver (userspace input device driver) that reads the resolution from the framebuffer device.

Strictly speaking we must not break ts_uinput behaviour and, if anything at all, write a different one, that uses the input device driver only.

Only in case we could verify that it simply always is the same on Linux, we could change ts_uinput. That's the question.

There's no simple switch from one to the other in ts_uinput, but we could add an option... That's probably the first step here.

**Comment by craftyguy** [comment]
Oh ok. Maybe I misunderstood your original question. It seems that if we're using `linear` that there would be no change to behavior regardless of whether you're reading resolution from fbdev or directly from the touch device?

**Comment by merge** [comment]
Absolutely. If you change resolution values, you'd need to re-calibrate though.
