### ISSUE TITLE
linear / calibfile: add support for rotated calibration

### ISSUE THREAD

**Issue by merge** [kergoth/tslib#128]
make our calibration file and linear transformation aware that pixels were rotated (using `ts_calibrate -r <rotate_value>`), i.e. _transform back to normal_, to leave transformation to toolkit/gui. make this optional, adding `rot` to linear for example.

**Comment by xoduddk123** [comment]
Hello,

I am using [xf86-input-tslib](https://github.com/merge/xf86-input-tslib) in X11.
In X11, [xf86-video-fbdev](https://github.com/freedesktop/xf86-video-fbdev) and [xf86-video-fbturbo](https://github.com/ssvb/xf86-video-fbturbo) support screen rotation through the "[Rotate](https://linux.die.net/man/4/fbdev)" option.
```
Section "Device"
        Identifier      "FBTURBO"
        Driver          "fbturbo"
        Option          "fbdev" "/dev/fb0"
        Option          "Rotate" "CCW"
        Option          "SwapbuffersWait" "false"
EndSection
```

I calibrate using ts_calibrate in the "NONE" state.
And I found that using "Rotate" in xf86-video-* would cause the calibration to be out of order.

Before I saw this issues, I tried to convert the touch value in xf86-input-tslib.
But I changed my mind when I saw this issues.

Currently I am using the following modified source.(Only tested on X11.)
https://github.com/xoduddk123/tslib/commit/c8df23336b5ca3cb6e23bad67e8b151dc252728f
The source has a prerequisite that it runs ts_calibrate only in the forward direction(NONE).

I hope this trail will help people with problems like me before tslib 2.0 comes out.

I'm sorry I do not have enough English.

thanks

**Comment by merge** [comment]
what do you mean by "NONE" state of `ts_calibrate`?. Do you mean you don't use the `-r` option?

I'm almost finished implementing this. It'll be quite straight-forward. ts_calibrate will (technically, internally) ignore screen-rotation, but save the value to the calibfile `TSLIB_CALIBFILE`. The `linear` filter module will by default read exactly that value and apply the rotation. And to be able to overwrite it, it'll have exactly the `rot` parameter you mentioned.

thanks for your report.

**Comment by xoduddk123** [comment]
Yes, "NONE" means that the `-r` option is not used when executing `ts_calibrate`. :)
thanks

**Comment by merge** [comment]
ok. what is implemented now is: you can use `-r` for calibration. by default, `linear` will apply that rotation (during calibration), but you can overwrite it using the `rot` parameter.

In your case, in order to have the same situation as you have it now, you could: `ts_calibrate -r 1` (or whatever rotation) and `module linear rot=0` in your ts.conf to have unrotated input values.

this is unreleased, scheduled to be part of tslib 1.18.
