### ISSUE TITLE
rewrite module_raw input against libevdev

### ISSUE THREAD

**Issue by merge** [kergoth/tslib#129]
self explanatory I guess. Adding a build-dependency here, _only if input is enabled_, really would improve quality: https://freedesktop.org/wiki/Software/libevdev/

**Comment by skirk** [comment]
Is the benefit of using libevdev that it provides cleaner interface to access data etc?
Asking because the stack is still a bit hazy for me.

**Comment by merge** [comment]
we'll definitely add a new `module_raw input-evdev` that should get built when libevdev is available at build-time... and that probably only for shared-lib builds.
