### ISSUE TITLE
ts_calibrate not closing fb/ts properly in validation mode

### ISSUE THREAD

**Issue by pfink-christ** [kergoth/tslib#142]
Hi,
I want to discuss the expected behavior of ts_calibrate when used in --validate mode.

The application now stays visually open after completion showing "passed/failed" without calling close_framebuffer() and ts_close() which might impact the system after use of ts_calibrate [ -> e.g. chvt hangs when ts_calibrate doesn't close the framebuffer properly].
I would like ts_calibrate --validate to close everything correctly.

I committed the bare necessary changes in #https://github.com/pfink-christ/tslib/commit/09808c632a5fd44e5b08e481e9cc9359ed051981 but this seems to be a quick shot solution only. This is because the final screen showing "passed/failed" cannot be seen anymore.

Maybe we could add a timeout (configurable with an option or hard coded to something like 5s). Or is the expected behavior to keep this screen forever (like it is now)?

What are your opinions?

I can make a pull request using my already committed solution or implement the behavior we agree on here.

Thanks,
Peter

**Comment by merge** [comment]
yes, good point. It's expected, but actually this issue in the current implementation. We can and probably should change that. I'd like a commandline option, with a default of 5s, and recreate the current behaviour if "timout 0" is set. (of course that option should require --validate too).

I'd be happy about a PR to discuss.

**Comment by pfink-christ** [comment]
I have another proposal:
argument: -s / --timeout
-1 -> former behavior (no timeout)
0 -> no result screen at all
>0 -> timeout in secs
What do you think?
