### ISSUE TITLE
Patch "Needed" for sun4i_ts?

### ISSUE THREAD

**Issue by GeorgeIoak** [kergoth/tslib#16]
I'm working on a A10 based board (Cubieboard) and working with a resistive touch screen directly connected to the A10. If I compile your library and run ts_calibrate it automatically steps through and when it returns I see a message about "Selected device is not a touchscreen"

If I apply this patch, https://github.com/OLIMEX/OLINUXINO/blob/master/SOFTWARE/A13/TOUCHSCREEN/tslib.patch I can get ts_calibrate to work but I'm not sure if this is the proper way to "fix" your code.

**Comment by merge** [comment]
your patch goes in the right direction, but doesn't implement the protocol correctly. Pressure should be derived from TOCH_MAJOR / WIDTH_MAJOR. Support for this is on my list.

**Comment by merge** [comment]
Actually, in case there isn't a standard way of calculating pressure from touch_major/width_major, I think we shouldn't do it. There might be, and I'm investigating, but if not, we would be better off, passing those values to the user as-is and using pressure internally like we always did.

In that case, for ts_read() we would not be able to use them. But for ts_read_mt(), coming soon, we would.

But yes. The check for ABS_X or ABS_Y is wrong. thanks!!

**Comment by merge** [comment]
Your device should be usabe with today's master branch. Forgot to reference the issue, but device-checking is fixed now.

Regarding ABS_MT_TOUCH_MAJOR, there is *no* standard way of calculating pressure. The pressure value coming from devices directly is arbitrary, but if not needed, we won't invent a pressure value from touch_major. Hope that work for you.

Thanks for you help!
