### ISSUE TITLE
Include ts_finddev and inputattach utils (Buildroot patches)

### ISSUE THREAD

**Issue by yegorich** [kergoth/tslib#18]
Buildroot has a patch to add ts_finddev and inputattach utils (http://git.buildroot.net/buildroot/tree/package/tslib). Does it make sense to include them in the official library?

**Comment by merge** [comment]
What speaks against including them? Are they anywhere else? I plan to fork tslib, with them included, among much more.

**Comment by kergoth** [comment]
I don't see any reason to oppose their inclusion, they would seem to add value.

**Comment by merge** [comment]
actually, inputattach is part of linuxconsole project: https://sourceforge.net/projects/linuxconsole/ but I'll add (and fix) ts_finddev for it to be included in an upcoming 1.2 release.

Other than that, I guess the right thing would be to ask buildroot to include this linux-console package.

**Comment by merge** [comment]
ts_finddev is added. inputattach, as I see it, has to be clarified on the buildroot list. I think this issue's author wasn't really asking for adding code that is already part of another project, so I'll go ahead and close this.
