### ISSUE TITLE
Problem static compiling ...

### ISSUE THREAD

**Issue by teratux** [kergoth/tslib#23]
I'm trying to statically compile the test suite: ts_calibrate mainly ...

The way I see it there are two options defined in the configure.ac: --enable-static and --enabled-shared.   I tried passing --enable-static=yes and --enable-shared=no, but still those options don't create static binaries for the files in the tests directory.  This is the configure line:

./configure --target=arm-linux --host=arm-linux --build=x86_64-unknown-linux-gnu --prefix=/usr --exec-prefix=/usr --sysconfdir=/etc --program-prefix= --disable-gtk-doc --disable-ipv6 --enable-static --disable-shared --enable-static=yes --enable-shared=no

 In my particular application a user needs to calibrate the screen from time to time, so it is a mandatory option.  My whole system is compiled with uClibc and static linkage, except this particular binary.

Any guide on how to accomplish this ?? 
Thanks in advance

**Comment by BennyBread** [comment]
Hi, this is my configure call:

./configure CC=/usr/local/gcc-linaro-arm-linux-gnueabihf-4.8-2014.04_linux/bin/arm-linux-gnueabihf-gcc CXX=/usr/local/gcc-linaro-arm-linux-gnueabihf-4.8-2014.04_linux/bin/arm-linux-gnueabihf-g++ -host=arm-linux-gnueabihf target=arm-linux-gnueabihf -enable-static=yes -enable-shared=yes -prefix=/opt/tslib/

I get these files after make + make install:

lrwxrwxrwx 1 debian admin   18 Jul 28 14:49 libts-1.0.so.0 -> libts-1.0.so.0.0.0*
-rwxr-xr-x 1 debian admin  10K Jul 28 14:49 libts-1.0.so.0.0.0*
-rw-r--r-- 1 debian admin  15K Jul 28 14:49 libts.a
-rwxr-xr-x 1 debian admin  934 Jul 28 14:49 libts.la*
lrwxrwxrwx 1 debian admin   18 Jul 28 14:49 libts.so -> libts-1.0.so.0.0.0*

The "libts.a" file should be the static library I think.

Maybee this helps you.

Regards,Ben

**Comment by merge** [comment]
I'll close this now due to the age and the changes in the codebase since. 2,5 year ago was asked for guidence. Please open a new issue and ask anything when you're running a recent version of tslib.

**Comment by merge** [comment]
It's a little late, but what you where maybe looking for, is something like this

`./configure --disable-shared --enable-static --enable-input=static --enable-pthres=static --enable-dejitter=static --enable-[whatever you need]=static ...`

to have one libts.a with everything built in
