### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by MarkJonas** [kergoth/tslib#26]
I want to use [Sourcegraph](https://sourcegraph.com) for tslib code search, browsing, and usage examples. Can an admin enable Sourcegraph for this repository? Just go to https://sourcegraph.com/github.com/kergoth/tslib. (It should only take 30 seconds.)

Thank you!

**Comment by kergoth** [comment]
Given that C isn't currently a supported language by SourceGraph or srclib, I don't really see the point.
