### ISSUE TITLE
ts_calibrate fix for the ARGB8888 color encoding

### ISSUE THREAD

**Issue by sposelenov** [kergoth/tslib#27]
Hello,

It looks like the current ts_\* utilities don't support transparency bits (alpha channel) of the colors encoding, as it returned by FBIOGET_FSCREENINFO. I fixed this and would like to provide a patch. How could I do that without going into "pull request"? Is there a mailing list where I could just post the patch?

Regards,
Sergei

**Comment by merge** [comment]
there is no mailing list I'm aware of. you can attach the patch file here though, if still relevant.

**Comment by sposelenov** [comment]
Hi, thanks for the note. Attaching the patch.
-S
[tslib-transp.patch.txt](https://github.com/kergoth/tslib/files/602815/tslib-transp.patch.txt)
