### ISSUE TITLE
ts_read() clarification

### ISSUE THREAD

**Issue by robgreger** [kergoth/tslib#33]
I have the following debug print. I would think that ts_read() would return both raw entries but it is only returning the last entry. Is this the intended operation?
RAW---------------------> 3078 2818 192 186.254589
RAW---------------------> 0 0 0 186.301727
VARIANCE----------------> 3078 2818 192
VARIANCE----------------> 3078 2818 0
BEFORE CALIB--------------------> 3078 2818 192
BEFORE CALIB--------------------> 3078 2818 0
**TS_READ----> x = 635, y = 180, pressure = 192** <---Only one sample is being returned.

**Comment by merge** [comment]
I just didn't print all received samples, like the plugins do. I think this wasn't intended. I forgot to mention this issue, but this is changed in master now.
