### ISSUE TITLE
autogen.sh issue

### ISSUE THREAD

**Issue by neostar63** [kergoth/tslib#40]
executing the autogen.sh script results in failure:
`autoreconf: 'configure.ac' or 'configure.in' is required`

It appears that the syntax of the autoreconf command is off, should 'pwd' really be "$(pwd)" or some derivative of that?

**Comment by kergoth** [comment]
``pwd`` and `$(pwd)` are equivalent in every shell. It sounds like you just didn't run it from inside the tslib source tree.

**Comment by neostar63** [comment]
I cloned tslib and navigated to that folder and ran autogen.sh inside of the folder. Are you saying I should be executing the script from inside the src folder instead of the root for the project?

**Comment by neostar63** [comment]
looking at it closer it looks like it should have been `pwd`/m4 instead of single quotes.

**Comment by neostar63** [comment]
I apologize for the confusion, this must have been something on my end.
