### ISSUE TITLE
tslib 1.1 with egalax 7 inch touchscreen

### ISSUE THREAD

**Issue by farfons** [kergoth/tslib#43]
hi, i've tried the tslib from git with a 7 inch egalax touchscreen (oeef:0001) in a Daphile distro. I can't calibrate nor with the tslib plugin (the system becomes unresponsive and i can only force the shutdown) nor with the "input" option in the ts.conf (appears the message `selected device is not a touchscreen (must support ABS and KEY event types`) can i apply any patch or set any other variable to solve the issue? thanks

**Comment by merge** [comment]
could you post an output of evtest, selecting the original device's input device?

**Comment by merge** [comment]
You should be able to use the "input" option in ts.conf now, with version 1.3-rc1

**Comment by merge** [comment]
well. in case you have problems using the latest version, please open a new issue. thanks!
