### ISSUE TITLE
[repost] variance.c causing missing pen release events

### ISSUE THREAD

**Issue by speakman** [kergoth/tslib#5]
(I accidentally closed my first posted issue, and there seems to be no way to unclose it. So here's a repost:)

In `variance_read()` there's a special case where `cur.pressure == 0`, it's supposed to "flush the queue" (according to the comments).

But due to the code construction below `acceptsample:`, the **last** sample is put to the out queue, which makes the **actual** pen release sample get lost when `count == (n-1)`.

I did a test with:
    samp[count++] = cur;
    return count;
instead of
    goto acceptsample;
which worked fine here, but I'm not sure that's a proper solution for this bug.

**Comment by speakman** [comment]
3,5 years later. tslib is still widespread and the default tool for touchscreens for many platforms and it still drops the release samples frequently. I'm _really_ not blaming @kergoth here, I'm just a bit fascinated no one seems to have issues with this. :)

**Comment by robgreger** [comment]
I can definitely see where your issue would occur if variance_read is not being called repeatedly. Could you detail what you did to discover the problem? In my testing using ts_print, the filter gets repeatedly called with nr equal to 1 even if I hold the screen and produce multiple events.

I added a debug print statement to the section of code where (cur.pressure == 0) and it looks like after the raw pen release event, that the filter goes through this section twice. The first time through, it produces a sample with pressure !=0. The second time through it produces the same sample with pressure == 0.

**Comment by kergoth** [comment]
Sorry for the delay on this, at this point about all I do with the project is apply patches folks send my way -- I no longer have any hardware with which to test tslib, so any issues, particularly thorny ones, are difficult to dive into. If anyone wants to step up and take over the project's maintenance, I'd be more than willing to hand it over :)

**Comment by merge** [comment]
@kergoth Just so you know, I'm working on tslib for 2 months now. I have some hardware and the need for multitouch in tslib, so I added a user ABI ts_read_mt() and read_mt() as API for plugins, wrote read_mt() for plugins, added new plugins.

I have plans to put in on github after some more testing or even some written test cases.

My plan would be to fork and increment the major version to 2. But now that I read you want to hand over the project, there would be no need to change the major version number.

Anyhow, we have a few weeks still, but why not coordinate this early, so.

thanks for all your work!

**Comment by merge** [comment]
On this specific issue: I'm working on implementing multitouch for the relevant plugins. The variance plugin is the only one I don't port. Actually on capacitive touchscreens the variance filter has problems with correct press/release propagation and I disable it. And for multitouch, things would become quite complicated, if even possible to do here.

what device are you using? are you absolutely sure you need the variance filter? if needed, we could think about coming up with a simpler 1:1 filter.

**Comment by speakman** [comment]
This was some time ago. IIRC I just skipped the variance filter as a whole.

**Comment by robgreger** [comment]
?I'm using a resistive touch screen without multitouch that is quite noisy. I'm not sure I need the variance filter. I will test without it.

Rob Greger
Otis Elevator Company
Software Engineer
Office: 860-676-6248
E-Mail: Robert.Greger@otis.com<mailto:Robert.Greger@otis.com>
________________________________

**Comment by merge** [comment]
@robgreger what exact problem do you have with your device using the variance filter? I think yours should work.

**Comment by robgreger** [comment]
?The variance filter with the fix I implemented does work for me. I thought the question was whether I actually needed it.


Rob Greger
Otis Elevator Company
Software Engineer
Office: 860-676-6248
E-Mail: Robert.Greger@otis.com<mailto:Robert.Greger@otis.com>
________________________________

**Comment by merge** [comment]
sorry, I was asking speakman who opened this issue. Maybe code comment or debug printf to let the user know about possible problems with capacitive touchscreens would be sufficient to close this issue.

**Comment by merge** [comment]
I tested again and think the change you posted is actually the right thing to do here, so applied. if pressure == 0, we should submit the sample. period. everything else regarding pressure is handled by other plugins.

**Comment by speakman** [comment]
Have you made a commit already? Or can I make it? Just for being part in the project. :-)

**Comment by merge** [comment]
It's already committed. But I took it from you, so you are part of the project. Just see the logs.

**Comment by speakman** [comment]
Oh. It looks like @robgreger turned my description into a commit, which is the one merged. I never did a complete commit since I wanted to discuss the issue first. Glad it got fixed. :)

**Comment by merge** [comment]
Ah, I got confused here. Sorry you didn't make it in this time, but it's not important who fixes it, as long it's fixed correctly. Closed, but if you have problems while testing the current master's variance filter now, I'm happy to see a new issue.
