### ISSUE TITLE
Predefined device name for touchscreen @ embedded platforms 

### ISSUE THREAD

**Issue by filug** [kergoth/tslib#61]
I'm using _tslib_ in some of my embedded projects and always I have an issue with _touchscreen device file name_ configuration for _tslib_.

_tslib_ will automatically "detect" touchscreen if it will be available as:

- `/dev/input/event0`,
- `/dev/touchscreen/ucb1x00`.

In my case `/dev/input/event0` either `/dev/touchscreen/ucb1x00` doesn't point to the touchscreen. Depends on the project configuration (for example how many HW buttons I have) it is - let's say `/dev/input/event3`.

My practice in such case is to:

1. create udev rule which will create simlink `/dev/input/touchscreen` to the detected `/dev/input/event*` touchscreen,
1. configure tslib via `TSLIB_TSDEVICE=/dev/input/touchscreen` env.

@kergoth Can you consider to extend list of "predefined" _touchscreen device files_ by something generic like `/dev/input/touchscreen` (or something else with better name)? This will at least eliminate 2nd step from the _setup touchscreen_ list.

If you agree I can prepare PR - otherwise I will continue to use _tslib_ as described above (or might be you have some hint how to solve described problem in more clever way?).

**Comment by merge** [comment]
We have the same problem. I'll look at it on monday, but feel free to send a PR for selecting /dev/input/touchscreen before the old defaults we can discuss.
