### ISSUE TITLE
input-raw: device is re-checked on every read

### ISSUE THREAD

**Issue by jampy** [kergoth/tslib#8]
In plugins/input-raw.c there is this piece of code at the top of ts_input_read():

``` c
  if (i->sane_fd == 0)
    i->sane_fd = check_fd(i);
```

However, `check_fd()` returns zero on a compatible device, meaning that `sane_fd` remains zero and `check_fd()` gets called again and again on each read, resulting in lots of IOCTLs whenever input events come in. Not a real problem, but still....

I guess, as the name of the variable implies, `check_fd()` should return the file descriptor (`i->module.dev->fd`) on success?

**Comment by vpeter4** [comment]
What about initializing i->sane_fd to -1 and check if value is -1? Then check_fd() would be called only once on first call.

**Comment by merge** [comment]
It's definitely a place that could be improved but it's not so easy. If the device doesn't use pressure key codes, for example, check_fd() sets the pressure value to what users expect. So one would have to spit things up a bit.

**Comment by merge** [comment]
done and most likely part of the next release.
