### ISSUE TITLE
project organisation / tslib.org / mailing list

### ISSUE THREAD

**Issue by merge** [kergoth/tslib#82]
First of all: **This github repository will stay the official place for development and releases!**
... as long as possible. there's no real reason to change in sight.

Primarily I want to have a mailing list again. But this would then be a random second place of development besides github. I also tought about putting random unofficial binary package up somewhere. Also, there is now a backup mirror of this repository at gitlab and things would be a total mess :) So: there is http://www.tslib.org/ now.

tslib.org should stay one simple index.html file, pointing to everything tslib. (it need a logo though :). Furthermore, *despite* having the official development in github, I'd love to be completely independent of it. We explicitely use github's issue tracker, but that's it.

bla bla. That's my todo list:

 - [x] register http://tslib.org
 - [x] register https://gitlab.com/tslib/tslib (only mirrors this repo once a day)
 - [x] upload release tarballs to gitlab too
 - [x] remove unnecessary absolute paths that include github.com
 - [x] have a mailing list (where?) and a link at tslib.org
 - [x] document everything for future maintainers

**Comment by ClayMontgomery** [comment]
Regarding the need for a logo, how about something like this:

![image](https://cloud.githubusercontent.com/assets/10004476/23968658/a4f0ff6e-0991-11e7-8741-9d8f0e188023.png)

Many logos like this are available here for just a few dollars:

https://www.iconfinder.com/icons/351220/finger_fingers_gesture_hand_ripple_tap_touch_wave_icon

**Comment by merge** [comment]
That's awfully nice to have an example! To be honest, I have an idea. I'd like it to be basically the name "tslib", but maybe really drawn by hand, and the "b" to be a hand, similar to your image :)

I can't explain to too well, but the drawn "tslib" word could have some hints to x/y math stuff, hm. Maybe I should get a pen and post roughly what I mean. I'll do sometime soon.

**Comment by merge** [comment]
by the way. That's what I'm thinking about: https://github.com/kergoth/tslib/issues/73 what would you say?

**Comment by merge** [comment]
2a8b968 add the mailing list to all relevant pages
