### ISSUE TITLE
properly draw our logo

### ISSUE THREAD

**Issue by merge** [kergoth/tslib#89]
our logo is basically a draft outline :) If you have the digital drawing skills to create a beautiful proper SVG file following the idea of the current one, _please_ let us know!

**Comment by rrcha** [comment]
Not the best at vector graphics in the world, but I had a go :)   Let me know if you would like the SVG.  Saw the request on the pmOS forums.

![tslib logo svg](https://user-images.githubusercontent.com/33532795/32637253-12b62ab8-c5b9-11e7-86ba-51491a85b36f.png)

**Comment by merge** [comment]
That's awesome! Thanks for doing this. Could I ask for a 2nd version with basicaly 2 changes?

* lines of hand and letters the same strength
* background raster removed

and do _you_ like it? Any idea for a change in general?

cool

**Comment by craftyguy** [comment]
I'm not the (magnificent!) submitter of this, but I quite like the logo!

**Comment by merge** [comment]
And yes, if I were to replace the logo, I'd only want to do it with an SVG image.

**Comment by rrcha** [comment]
I've made a few changes per request as attached:

![tslib logo v2](https://user-images.githubusercontent.com/33532795/32655187-e33594a0-c60c-11e7-893d-e691aebc81f1.png)

As per the design, yes, I like it!  I can't think of any changes I'd make.

As for the favicon, maybe something like this?

![tslib favicon](https://user-images.githubusercontent.com/33532795/32655581-716267ac-c60e-11e7-8310-860afde0af3d.png)

**Comment by merge** [comment]
I like it :) If you'll provide the svg files and permissions to resize and use them as fit, I guess I'll take them.

What do others think?

**Comment by rrcha** [comment]
Sure. I've [uploaded the vector (and raster) versions of the file here](https://github.com/rrcha/TSLIB-logo) and waived all rights to the file.

It would be nice to get a mention in your contributors list though!

**Comment by merge** [comment]
Oh sure. Please give me your name and email address in order to add you to the THANKS file.

**Comment by rrcha** [comment]
Ravi Chandarana (ravichandarana@rocketmail.com)

Many thanks!

**Comment by merge** [comment]
One more thing: Would you resize the logo to be smaller for me? About 2/3 of the current size maybe. I just saw that it's not as easy as I thought -.-

You can push a commit to your repository, overwriting the svg file of course.

thanks!

**Comment by rrcha** [comment]
Ok, done!

**Comment by merge** [comment]
Wow, I really think this is totally awesome! If you ask me this improves the project quite a bit. This is a pretty high quality product and now we have a logo that can represent it properly.

thanks!

**Comment by rrcha** [comment]
My pleasure.  Best wishes for the project!
